name: Automated Code Review

on:
  pull_request:
    types: [ opened, synchronize, reopened ]

jobs:
  code-review:
    runs-on: ubuntu-latest

    permissions:
      pull-requests: write
      statuses: write
      contents: read

    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Run automated code review
        uses: vladan-me/ci@v0.1.0
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          review_api_url: ${{ secrets.REVIEW_API_URL }}
          review_api_key: ${{ secrets.REVIEW_API_KEY }}
          # Optional: customize comment formatting
          # include_ai_assist_inline: 'true'
          # include_ai_assist_summary: 'false'
          # max_line_width: '100'
